-- ==============================================================================
-- Travel Booking Web Application - Production PostgreSQL Schema
-- Database: PostgreSQL 14+ compatible
-- Tables: app_users, destination, travel_package, booking, payment, review
-- ==============================================================================

-- 1. User Table (app_users)
CREATE TABLE IF NOT EXISTS public.app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    role VARCHAR(255) CONSTRAINT app_users_role_check CHECK (role IN ('USER', 'ADMIN'))
);

-- 2. Destination Table (destination)
CREATE TABLE IF NOT EXISTS public.destination (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    country VARCHAR(255),
    description VARCHAR(255)
);

-- 3. Travel Package Table (travel_package)
CREATE TABLE IF NOT EXISTS public.travel_package (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description TEXT,
    price DOUBLE PRECISION,
    duration INTEGER,
    available_seats INTEGER,
    destination_id BIGINT CONSTRAINT fk_travel_package_destination REFERENCES public.destination(id)
);

-- 4. Booking Table (booking)
CREATE TABLE IF NOT EXISTS public.booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_date DATE,
    number_of_people INTEGER,
    total_amount DOUBLE PRECISION,
    status VARCHAR(255),
    expires_at TIMESTAMP(6) WITHOUT TIME ZONE,
    travel_package_id BIGINT CONSTRAINT fk_booking_travel_package REFERENCES public.travel_package(id),
    user_id BIGINT CONSTRAINT fk_booking_user REFERENCES public.app_users(id)
);

-- 5. Payment Table (payment)
CREATE TABLE IF NOT EXISTS public.payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount DOUBLE PRECISION,
    payment_method VARCHAR(255),
    status VARCHAR(255),
    payment_date TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    razorpay_order_id VARCHAR(255),
    razorpay_payment_id VARCHAR(255),
    razorpay_signature VARCHAR(255),
    booking_id BIGINT NOT NULL CONSTRAINT fk_payment_booking REFERENCES public.booking(id)
);

-- 6. Review Table (review)
CREATE TABLE IF NOT EXISTS public.review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating INTEGER,
    comment VARCHAR(255),
    travel_package_id BIGINT NOT NULL CONSTRAINT fk_review_travel_package REFERENCES public.travel_package(id),
    user_id BIGINT NOT NULL CONSTRAINT fk_review_user REFERENCES public.app_users(id)
);

-- ------------------------------------------------------------------------------
-- Indexes for Performance & Query Optimization
-- ------------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_booking_user_id ON public.booking(user_id);
CREATE INDEX IF NOT EXISTS idx_booking_status_expires ON public.booking(status, expires_at);
CREATE INDEX IF NOT EXISTS idx_payment_booking_id ON public.payment(booking_id);
CREATE INDEX IF NOT EXISTS idx_payment_razorpay_order_id ON public.payment(razorpay_order_id);
CREATE INDEX IF NOT EXISTS idx_payment_razorpay_payment_id ON public.payment(razorpay_payment_id);
CREATE INDEX IF NOT EXISTS idx_travel_package_destination_id ON public.travel_package(destination_id);
CREATE INDEX IF NOT EXISTS idx_review_travel_package_id ON public.review(travel_package_id);
CREATE INDEX IF NOT EXISTS idx_review_user_id ON public.review(user_id);
